version: "3.6"
services:
  mvp:
    build: ./frontend/build

    volumes:
      - .frontend/app:/app

    restart: always
    env_file:
      - .env

    ports:
      - "${FRONTEND_PORT}:8080"

    networks:
      - default