version: "2.4"
services:
  frontend:
    build: ./frontend/build

    volumes:
      - .frontend/app:/app

    restart: always
    env_file:
      - .env

    ports:
      - "${FRONTEND_PORT}:8080"

    networks:
      - internal-network

  backend:
    build: ./backend/build

    volumes:
      - ./backend/app:/app
    restart: always

    env_file:
      - .env
      - ./backend/.env

    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - internal-network

  model_deployment:
    build: ./model_deployment/build
    runtime: nvidia
    shm_size: '6gb'

    volumes:
      - ./model_deployment/app:/app
    restart: on-failure
    env_file:
      - .env
      - ./model_deployment/.env

    ports:
      - "${MODEL_DEPLOYMENT_PORT}:8000"
    command: serve run --host 0.0.0.0 main:backend

    networks:
      - internal-network


  minio_backend:
    image: minio/minio:latest
    hostname: miniobackend
    container_name: minio_backend
    restart: always
    volumes:
      - ./infrastracture_data/minio/data/:/data
    env_file:
      - .env
    ports:
      - "${MINIO_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: [ "server",  "--console-address", ":9001" , "/data/" ]
    networks:
      - internal-network

  createbuckets:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      - minio_backend
    networks:
      - internal-network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://miniobackend:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
      /usr/bin/mc mb myminio/${MINIO_BUCKET};
      /usr/bin/mc policy set public myminio/${MINIO_BUCKET};
      exit 0;
      "


  postgres_backend:
    container_name: postgres_backend
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./infrastracture_data/postgres:/data/postgres
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    networks:
      - internal-network

networks:
  internal-network:
    name: mfdp-2023_default
    external: True
